#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

# the "app_lucky_number" route name is not important yet
hello_the_world:
    path:       /
    controller: App\Controller\AdvertController::index

Sing_in: 
  path: /Sign_in
  controller: App\Controller\AdvertController:Sign_in